Repository Teddy-Hackers/devtools-course-practice, pull requests merged in 2023-05, with the labels that each got.

#125 Антонова - Лабораторная работа #1
  modules/complex-number/test/test_ANTONOVA_ANASTASYA_complex_number.cpp
Labels: Ready for merge, lab 1

#117 Колесов - Лабораторная работа #3
  modules/binary-search/CMakeLists.txt
  modules/binary-search/CTestTests.txt
  modules/binary-search/application/CMakeLists.txt
  modules/binary-search/application/binary_search.cpp
  modules/binary-search/include/search_application.h
  modules/binary-search/src/search_application.cpp
Labels: Ready for merge, lab 3

#126 Селиванкин - Лабораторная работа #3
  modules/caesar-cipher/CMakeLists.txt
  modules/caesar-cipher/CTestTests.txt
  modules/caesar-cipher/application/CMakeLists.txt
  modules/caesar-cipher/application/caesar-cipher.cpp
  modules/caesar-cipher/include/cipher_application.h
  modules/caesar-cipher/src/cipher_application.cpp
Labels: Ready for merge, lab 3

#123 Семенова - Лабораторная работа №3
  modules/priority-queue/CMakeLists.txt
  modules/priority-queue/CTestTests.txt
  modules/priority-queue/application/CMakeLists.txt
  modules/priority-queue/application/application.cpp
  modules/priority-queue/include/pq_app.h
  modules/priority-queue/include/priority_queue.h
  modules/priority-queue/src/CMakeLists.txt
  modules/priority-queue/src/pq_app.cpp
  modules/priority-queue/src/priority_queue.cpp
  modules/priority-queue/test/CMakeLists.txt
  modules/priority-queue/test/test_main.cpp
  modules/priority-queue/test/test_priority_queue.cpp
Labels: Ready for merge, lab 3

#127 Елистратов - Лабораторная работа №2
  dashboard/build/CMakeCache.txt
  dashboard/build/CMakeFiles/3.26.0-rc4/CMakeSystem.cmake
  dashboard/build/CMakeFiles/CMakeConfigureLog.yaml
  dashboard/build/CMakeFiles/cmake.check_cache
  dashboard/build/Testing/20230501-1153/Build.xml
  dashboard/build/Testing/20230501-1153/Configure.xml
  dashboard/build/Testing/20230501-1153/Test.xml
  dashboard/build/Testing/Temporary/CTestCostData.txt
  dashboard/build/Testing/Temporary/LastBuild_20230501-1153.log
  dashboard/build/Testing/Temporary/LastConfigure_20230501-1153.log
  dashboard/build/Testing/Temporary/LastTest_20230501-1153.log
  dashboard/ctest_ext_notes_log.txt
  modules/complex-number-calculator/CMakeLists.txt
  modules/complex-number-calculator/include/complex_calculator.h
  modules/complex-number-calculator/src/CMakeLists.txt
  modules/complex-number-calculator/src/complex_calculator.cpp
  modules/complex-number-calculator/test/CMakeLists.txt
  modules/complex-number-calculator/test/test_complex_calculator.cpp
  modules/complex-number-calculator/test/test_main.cpp
Labels: lab 2

#124 Микерин И. - Лабораторная работа 1
  modules/complex-number/test/test_Mikerin_Ilya_complex_number.cpp
Labels: Ready for merge, lab 1

#121 Шокуров - Лабораторная работа #2
  modules/euler-function/CMakeLists.txt
  modules/euler-function/README.md
  modules/euler-function/include/euler_function.h
  modules/euler-function/src/CMakeLists.txt
  modules/euler-function/src/euler_function.cpp
  modules/euler-function/test/CMakeLists.txt
  modules/euler-function/test/test_euler_function.cpp
  modules/euler-function/test/test_main.cpp
Labels: Ready for merge, lab 2

#132 Гончарова - Лабораторная #1
  modules/complex-number/test/test_GONCHAROVA_ANNA_complex_number.cpp
Labels: Ready for merge, lab 1

#130 Яшина - Лабораторная работа #1
  modules/complex-number/test/test_YASHINA_ANASTASIA_complex_number.cpp
Labels: Ready for merge, lab 1

#60 Бочкарев - Лабораторная работа #1
  modules/complex-number/test/test_BOCHKAREV_VLADIMIR_complex_number.cpp
Labels: Ready for merge, lab 1

#136 Макаров - Лабораторная работа #2
  modules/fraction-calculator/CMakeLists.txt
  modules/fraction-calculator/include/fraction_calculator.h
  modules/fraction-calculator/include/fraction_number.h
  modules/fraction-calculator/src/CMakeLists.txt
  modules/fraction-calculator/src/fraction_number.cpp
  modules/fraction-calculator/test/CMakeLists.txt
  modules/fraction-calculator/test/test_Makarov_Danila_fraction_calculator.cpp
  modules/fraction-calculator/test/test_main.cpp
Labels: Ready for merge, lab 2

#80 Чубенко - Лабораторная работа #1
  modules/complex-number/test/test_Chubenko_Andrey_complex_number.cpp
Labels: Ready for merge, lab 1

#151 Кудряшов - Лабораторная работа #1
  modules/complex-number/test/test_KUDRYASHOV_NIKITA_complex_number.cpp
Labels: Ready for merge, lab 1

#143 Ермолаев - Лабораторная работа #2
  modules/AVL-Tree/CMakeLists.txt
  modules/AVL-Tree/include/AVLTree.h
  modules/AVL-Tree/src/AVLTree.cpp
  modules/AVL-Tree/src/CMakeLists.txt
  modules/AVL-Tree/test/CMakeLists.txt
  modules/AVL-Tree/test/test_AVL_Tree.cpp
  modules/AVL-Tree/test/test_main.cpp
Labels: Ready for merge, lab 2

#163 Гостеева - Лабораторная работа #1
  modules/complex-number/test/test_GOSTEEVA_EKATERINA_complex_number.cpp
Labels: Ready for merge, lab 1

#164 Пашина - Лабораторная работа #1
  modules/complex-number/test/test_PASHINA_ALINA_complex_number.cpp
Labels: Ready for merge, lab 1

#166 Попов - Лабораторная работа #2
  modules/quadrical-equal/CMakeLists.txt
  modules/quadrical-equal/include/quadrical_equal.h
  modules/quadrical-equal/src/CMakeLists.txt
  modules/quadrical-equal/src/quadrical_equal.cpp
  modules/quadrical-equal/test/CMakeLists.txt
  modules/quadrical-equal/test/test_Popov_Andrey_quadrical_equal.cpp
  modules/quadrical-equal/test/test_main.cpp
Labels: Ready for merge, lab 2

#152 Шокуров - Лабораторная работа #3
  modules/longest-increasing-subsequence/CMakeLists.txt
  modules/longest-increasing-subsequence/CTestTests.txt
  modules/longest-increasing-subsequence/application/CMakeLists.txt
  modules/longest-increasing-subsequence/application/longest_inc_subseq.cpp
  modules/longest-increasing-subsequence/include/longest_inc_subseq_application.h
  modules/longest-increasing-subsequence/src/longest_inc_subseq_application.cpp
Labels: Ready for merge, lab 3

#167 Мухин - Лабораторная работа #1
  modules/complex-number/test/test_Mukhin_Vadim_complex_number.cpp
Labels: lab 1

#168 Николаев - Лабораторная работа #2
  modules/odd-even-merge-batcher/CMakeLists.txt
  modules/odd-even-merge-batcher/include/odd_even_merge.h
  modules/odd-even-merge-batcher/src/CMakeLists.txt
  modules/odd-even-merge-batcher/src/odd_even_merge.cpp
  modules/odd-even-merge-batcher/test/CMakeLists.txt
  modules/odd-even-merge-batcher/test/test_main.cpp
  modules/odd-even-merge-batcher/test/test_odd_even_merge.cpp
Labels: lab 2

#173 Тычинин - Лабораторная работа #2
  modules/check_segments_intersection/CMakeLists.txt
  modules/check_segments_intersection/include/Point.h
  modules/check_segments_intersection/include/Segment.h
  modules/check_segments_intersection/include/check_segments_intersection.h
  modules/check_segments_intersection/src/CMakeLists.txt
  modules/check_segments_intersection/src/check_segments_intersection.cpp
  modules/check_segments_intersection/test/CMakeLists.txt
  modules/check_segments_intersection/test/test_main.cpp
  modules/check_segments_intersection/test/test_segments_intersection.cpp
Labels: Ready for merge, lab 2

#186 Микерин - Лабораторная работа 2
  modules/Dijkstra/CMakeLists.txt
  modules/Dijkstra/CTestTests.txt
  modules/Dijkstra/README.md
  modules/Dijkstra/include/Dijkstra.h
  modules/Dijkstra/src/CMakeLists.txt
  modules/Dijkstra/src/Dijkstra.cpp
  modules/Dijkstra/test/CMakeLists.txt
  modules/Dijkstra/test/test_Dijkstra.cpp
  modules/Dijkstra/test/test_main.cpp
Labels: Ready for merge, lab 2

#187 Мухин - Лабораторная Работа №2
  lab-guide/topics.md
  modules/Konverterandcalculator/CMakeLists.txt
  modules/Konverterandcalculator/include/Calculator.h
  modules/Konverterandcalculator/include/Converter.h
  modules/Konverterandcalculator/src/CMakeLists.txt
  modules/Konverterandcalculator/src/Calculator.cpp
  modules/Konverterandcalculator/src/Converter.cpp
  modules/Konverterandcalculator/test/CMakeLists.txt
  modules/Konverterandcalculator/test/test_Mukhin_Vadim_Calculator.cpp
  modules/Konverterandcalculator/test/test_main.cpp
Labels: Ready for merge, lab 2

#189 Никитин - Лабораторная работа #2
  modules/areas-of-figures/CMakeLists.txt
  modules/areas-of-figures/include/areas.h
  modules/areas-of-figures/src/CMakeLists.txt
  modules/areas-of-figures/src/areas.cpp
  modules/areas-of-figures/test/CMakeLists.txt
  modules/areas-of-figures/test/test_areas.cpp
  modules/areas-of-figures/test/test_main.cpp
Labels: Ready for merge, lab 2

#197 Макаров - Лабораторная работа #3
  modules/areas-of-figures/CMakeLists.txt
  modules/areas-of-figures/CTestTests.txt
  modules/areas-of-figures/application/CMakeLists.txt
  modules/areas-of-figures/application/areas.cpp
  modules/areas-of-figures/include/areas_application.h
  modules/areas-of-figures/src/areas_application.cpp
Labels: Ready for merge, lab 3

#188 Булгаков - Лабораторная работа #3
  modules/Dijkstra/CMakeLists.txt
  modules/Dijkstra/CTestTests.txt
  modules/Dijkstra/application/CMakeLists.txt
  modules/Dijkstra/application/dijkstra.cpp
  modules/Dijkstra/include/dijkstra_application.h
  modules/Dijkstra/src/dijkstra_application.cpp
Labels: lab 3

#194 Мухин-Лабораторная работа 3
  modules/fraction-calculator/CMakeLists.txt
  modules/fraction-calculator/CTestTests.txt
  modules/fraction-calculator/application/CMakeLists.txt
  modules/fraction-calculator/application/fraction_number.cpp
  modules/fraction-calculator/include/fraction_number_application.h
  modules/fraction-calculator/src/fraction_number_aplication.cpp
Labels: lab 3

#169 Еремин - Лабораторная работа #2
  modules/polynomial_calculator/CMakeLists.txt
  modules/polynomial_calculator/include/polynomial_calculator.h
  modules/polynomial_calculator/src/CMakeLists.txt
  modules/polynomial_calculator/src/polynomial_calculator.cpp
  modules/polynomial_calculator/test/CMakeLists.txt
  modules/polynomial_calculator/test/test_main.cpp
  modules/polynomial_calculator/test/test_polynomial_calculator.cpp
Labels: lab 2

#204 Ивлев - Лабораторная работа 2
  modules/prime-numbers-from-interval/CMakeLists.txt
  modules/prime-numbers-from-interval/include/prime_numbers_from_interval.h
  modules/prime-numbers-from-interval/src/CMakeLists.txt
  modules/prime-numbers-from-interval/src/prime_numbers_from_interval.cpp
  modules/prime-numbers-from-interval/test/CMakeLists.txt
  modules/prime-numbers-from-interval/test/test_main.cpp
  modules/prime-numbers-from-interval/test/test_prime_numbers_from_interval.cpp
Labels: Ready for merge, lab 2

#207 Юрин Евгений - Лабораторная работа №3
  modules/string-encoding-Base64/CMakeLists.txt
  modules/string-encoding-Base64/CTestTests.txt
  modules/string-encoding-Base64/application/CMakeLists.txt
  modules/string-encoding-Base64/application/string-encoder64.cpp
  modules/string-encoding-Base64/include/encoder_application.h
  modules/string-encoding-Base64/src/CMakeLists.txt
  modules/string-encoding-Base64/src/encoder_application.cpp
  modules/string-encoding-Base64/test/CMakeLists.txt
Labels: Ready for merge, lab 3

#218 Микерин - Лабораторная работа 3
  modules/int-radix-sort/CMakeLists.txt
  modules/int-radix-sort/CTestTests.txt
  modules/int-radix-sort/application/CMakeLists.txt
  modules/int-radix-sort/application/radix_main.cpp
  modules/int-radix-sort/include/radix_application.h
  modules/int-radix-sort/src/CMakeLists.txt
  modules/int-radix-sort/src/radix_application.cpp
Labels: Ready for merge, lab 3

#214 Митин - Лабораторная работа #2
  modules/gronsfeld-cipher/CMakeLists.txt
  modules/gronsfeld-cipher/include/gronsfeld_cipher.hpp
  modules/gronsfeld-cipher/src/CMakeLists.txt
  modules/gronsfeld-cipher/src/gronsfeld_cipher.cpp
  modules/gronsfeld-cipher/test/CMakeLists.txt
  modules/gronsfeld-cipher/test/test_MITIN_ROMAN_gronsfeld-cipher.cpp
  modules/gronsfeld-cipher/test/test_main.cpp
Labels: Ready for merge, lab 2

#210 Бинько - Лабораторная работа #2
  modules/hanoi-tower/CMakeLists.txt
  modules/hanoi-tower/include/hanoi_tower.h
  modules/hanoi-tower/src/CMakeLists.txt
  modules/hanoi-tower/src/hanoi_tower.cpp
  modules/hanoi-tower/test/CMakeLists.txt
  modules/hanoi-tower/test/test_Binko_Alexander_hanoi_tower.cpp
  modules/hanoi-tower/test/test_main.cpp
Labels: Ready for merge, lab 2

#215 Кудряшов - Лабораторная работа #3
  modules/longest_common_subsequence/CMakeLists.txt
  modules/longest_common_subsequence/CTestTests.txt
  modules/longest_common_subsequence/application/CMakeLists.txt
  modules/longest_common_subsequence/application/longest_common_subsequence.cpp
  modules/longest_common_subsequence/include/longest_common_subsequence_app.h
  modules/longest_common_subsequence/src/longest_common_subsequence_app.cpp
Labels: Ready for merge, lab 3

#220 Костерин - Лабораторная работа #2
  modules/code_vijener/CMakeLists.txt
  modules/code_vijener/include/code_vijener.h
  modules/code_vijener/src/CMakeLists.txt
  modules/code_vijener/src/code_vijener.cpp
  modules/code_vijener/test/CMakeLists.txt
  modules/code_vijener/test/test_kosterin_a_complex_number.cpp
  modules/code_vijener/test/test_main.cpp
Labels: Ready for merge, lab 2

#178 Лебединский - Лабораторная работа #1
  modules/complex-number/test/test_Lebedinskiy_Ilya_complex_number.cpp
Labels: Ready for merge, lab 1

#217 Симеунович - Лабораторная работа #1
  modules/complex-number/test/test_Simeunovic_Aleksandar_complex_number.cpp
Labels: Ready for merge, lab 1

#180 Терина - Лабораторная работа #2
  modules/Function_Eyler/CMakeLists.txt
  modules/Function_Eyler/include/Function_Eyler.h
  modules/Function_Eyler/src/CMakeLists.txt
  modules/Function_Eyler/src/Function_Eyler.cpp
  modules/Function_Eyler/test/CMakeLists.txt
  modules/Function_Eyler/test/terina_test_func_eyler.cpp
  modules/Function_Eyler/test/test_main.cpp
Labels: Ready for merge, lab 2

#225 Шипилов - Лабораторная работа #2
  modules/hashmap/CMakeLists.txt
  modules/hashmap/include/hashmap.h
  modules/hashmap/src/CMakeLists.txt
  modules/hashmap/src/hashmap.cpp
  modules/hashmap/test/CMakeLists.txt
  modules/hashmap/test/test_hashmap.cpp
  modules/hashmap/test/test_main.cpp
Labels: Ready for merge, lab 2

#223 Митин - Лабораторная работа #3
  modules/euler-function/CMakeLists.txt
  modules/euler-function/CTestTests.txt
  modules/euler-function/application/CMakeLists.txt
  modules/euler-function/application/main.cpp
  modules/euler-function/include/euler_function_app.hpp
  modules/euler-function/src/euler_function.cpp
  modules/euler-function/src/euler_function_app.cpp
  modules/euler-function/test/test_euler_function_app.cpp
Labels: Ready for merge, lab 3

#230 Бочкарев - Лабораторная работа #2
  modules/num-integral/CMakeLists.txt
  modules/num-integral/include/num_integral.h
  modules/num-integral/src/CMakeLists.txt
  modules/num-integral/src/num_integral.cpp
  modules/num-integral/test/CMakeLists.txt
  modules/num-integral/test/test_main.cpp
  modules/num-integral/test/test_num_integral.cpp
Labels: Ready for merge, lab 2

#226 Тарасова - лабораторная работа 2
  modules/volumes/CMakeLists.txt
  modules/volumes/include/Volumes.h
  modules/volumes/src/CMakeLists.txt
  modules/volumes/src/Volumes.cpp
  modules/volumes/test/CMakeLists.txt
  modules/volumes/test/main.cpp
  modules/volumes/test/test_volumes.cpp
Labels: Ready for merge, lab 2

#235 Лебединский - Лабораторная работа #2
  modules/triangle-basic-parameters/CMakeLists.txt
  modules/triangle-basic-parameters/CTestTests.txt
  modules/triangle-basic-parameters/include/lebedinskiy_ilya_triangle_basic_params.h
  modules/triangle-basic-parameters/src/CMakeLists.txt
  modules/triangle-basic-parameters/src/lebedinskiy_ilya_triangle_basic_params.cpp
  modules/triangle-basic-parameters/test/CMakeLists.txt
  modules/triangle-basic-parameters/test/test.cpp
  modules/triangle-basic-parameters/test/test_main.cpp
Labels: Ready for merge, lab 2

#236 Ивлев - Лабораторная работа #3
  modules/gronsfeld-cipher/CMakeLists.txt
  modules/gronsfeld-cipher/CTestTests.txt
  modules/gronsfeld-cipher/application/CMakeLists.txt
  modules/gronsfeld-cipher/application/gronsfeld-cipher.cpp
  modules/gronsfeld-cipher/include/gronsfeld_cipher_app.h
  modules/gronsfeld-cipher/src/gronsfeld_cipher_app.cpp
  modules/gronsfeld-cipher/test/test_gronsfeld-cipher_app.cpp
Labels: Ready for merge, lab 3

#244 Кругликова - Лабораторная работа #1
  modules/complex-number/test/test_KRUGLIKOVA_VALERIIA_complex_number.cpp
Labels: Ready for merge, lab 1

#239 Еремин - Лабораторная работа #3
  modules/hashmap/CMakeLists.txt
  modules/hashmap/CTestTests.txt
  modules/hashmap/application/CMakeLists.txt
  modules/hashmap/application/application.cpp
  modules/hashmap/include/hashmap.h
  modules/hashmap/include/hashmap_application.h
  modules/hashmap/src/hashmap_application.cpp
Labels: Ready for merge, lab 3

#252 Гончарова - Лабораторная 2
  modules/vector_3d/CMakeLists.txt
  modules/vector_3d/CTestTests.txt
  modules/vector_3d/include/vector_3d.h
  modules/vector_3d/src/CMakeLists.txt
  modules/vector_3d/src/vector_3d.cpp
  modules/vector_3d/test/CMakeLists.txt
  modules/vector_3d/test/test_main.cpp
  modules/vector_3d/test/test_vector_3d.cpp
Labels: Ready for merge, lab 2

#248 Устинов - Лабораторная работа #3
  modules/prime-numbers-from-interval/CMakeLists.txt
  modules/prime-numbers-from-interval/CTestTests.txt
  modules/prime-numbers-from-interval/application/CMakeLists.txt
  modules/prime-numbers-from-interval/application/prime_numbers_from_interval.cpp
  modules/prime-numbers-from-interval/include/prime_numbers_from_interval_app.h
  modules/prime-numbers-from-interval/src/prime_numbers_from_interval_app.cpp
  modules/prime-numbers-from-interval/test/test_prime_numbers_from_interval_app.cpp
Labels: Ready for merge, lab 3

#172 Уваркин - Лабораторная работа #2
  modules/sets/CMakeLists.txt
  modules/sets/include/set.h
  modules/sets/src/CMakeLists.txt
  modules/sets/src/set.cpp
  modules/sets/test/CMakeLists.txt
  modules/sets/test/test_main.cpp
  modules/sets/test/text_set.cpp
Labels: Ready for merge, lab 2

#232 Уваркин - Лабораторная работа #3
  modules/code_vijener/CTestTests.txt
  modules/code_vijener/application/code_vijener.cpp
  modules/code_vijener/include/code_vijener_application.h
  modules/code_vijener/src/code_vijener_application.cpp
Labels: Ready for merge, lab 3

#255 Миронов - Лабораторная работа #2
  modules/interpolation_search/CMakeLists.txt
  modules/interpolation_search/include/interpolation_search.h
  modules/interpolation_search/src/CMakeLists.txt
  modules/interpolation_search/src/interpolation_search.cpp
  modules/interpolation_search/test/CMakeLists.txt
  modules/interpolation_search/test/test_interpolation_search.cpp
  modules/interpolation_search/test/test_main.cpp
Labels: Ready for merge, lab 2

#261 Шипилов - Лабораторная работа #3
  modules/polynomial_calculator/CMakeLists.txt
  modules/polynomial_calculator/CTestTests.txt
  modules/polynomial_calculator/application/CMakeLists.txt
  modules/polynomial_calculator/application/application.cpp
  modules/polynomial_calculator/include/polynomial_calculator.h
  modules/polynomial_calculator/include/polynomial_calculator_application.h
  modules/polynomial_calculator/src/polynomial_calculator.cpp
  modules/polynomial_calculator/src/polynomial_calculator_application.cpp
Labels: Ready for merge, lab 3

#270 Французов - Лабораторная работа 2
  modules/KonverterFR/CMakeLists.txt
  modules/KonverterFR/include/Converter.h
  modules/KonverterFR/src/CMakeLists.txt
  modules/KonverterFR/src/Converter.cpp
  modules/KonverterFR/test/CMakeLists.txt
  modules/KonverterFR/test/test_Converter.cpp
  modules/KonverterFR/test/test_main.cpp
Labels: Ready for merge, lab 2

#265 Терина - Лабораторная работа #3
  modules/triangle-basic-parameters/CMakeLists.txt
  modules/triangle-basic-parameters/CTestTests.txt
  modules/triangle-basic-parameters/application/CMakeLists.txt
  modules/triangle-basic-parameters/application/application.cpp
  modules/triangle-basic-parameters/include/basic_param_tr.h
  modules/triangle-basic-parameters/src/CMakeLists.txt
  modules/triangle-basic-parameters/src/basic_param_tr.cpp
Labels: Ready for merge, lab 3

#273 Бинько - Лабораторная работа #3
  modules/KonverterFR/CMakeLists.txt
  modules/KonverterFR/CTestTests.txt
  modules/KonverterFR/application/CMakeLists.txt
  modules/KonverterFR/application/KonverterFR.cpp
  modules/KonverterFR/include/KonverterFR_application.h
  modules/KonverterFR/src/KonverterFR_application.cpp
Labels: Ready for merge, lab 3

#271 Никитин - Лабораторная работа #3
  modules/num-integral/CMakeLists.txt
  modules/num-integral/CTestTests.txt
  modules/num-integral/application/CMakeLists.txt
  modules/num-integral/application/num_integral.cpp
  modules/num-integral/include/num_integral_application.h
  modules/num-integral/src/num_integral_application.cpp
Labels: Ready for merge, lab 3

#258 Лапин - Лабораторная работа #1
  modules/complex-number/test/test_Lapin_Dmitriy_complex_number.cpp
Labels: Ready for merge, lab 1

#253 Яшина - Лабораторная #2
  modules/area_calculation/CMakeLists.txt
  modules/area_calculation/include/area_calculation.h
  modules/area_calculation/src/CMakeLists.txt
  modules/area_calculation/src/area_calculation.cpp
  modules/area_calculation/test/CMakeLists.txt
  modules/area_calculation/test/test_area_calculation.cpp
  modules/area_calculation/test/test_main.cpp
Labels: Ready for merge, lab 2

#268 Кругликова - Лабораторная работа 2
  modules/Matrix/CMakeLists.txt
  modules/Matrix/CTestTests.txt
  modules/Matrix/include/matrix.h
  modules/Matrix/src/CMakeLists.txt
  modules/Matrix/src/matrix.cpp
  modules/Matrix/test/CMakeLists.txt
  modules/Matrix/test/test_main.cpp
  modules/Matrix/test/test_matrix.cpp
Labels: Ready for merge, lab 2

#275 Французов - Лабораторная работа 3
  modules/check_segments_intersection/CMakeLists.txt
  modules/check_segments_intersection/CTestTests.txt
  modules/check_segments_intersection/application/CMakeLists.txt
  modules/check_segments_intersection/application/app.cpp
  modules/check_segments_intersection/include/check_segments_app.h
  modules/check_segments_intersection/src/CMakeLists.txt
  modules/check_segments_intersection/src/check_segments_intersection_app.cpp
Labels: Ready for merge, lab 3

#278 Попов - лабораторная работа #3
  modules/triangle-basic-parameters/CTestTests.txt
  modules/volumes/CMakeLists.txt
  modules/volumes/CTestTests.txt
  modules/volumes/application/CMakeLists.txt
  modules/volumes/application/application.cpp
  modules/volumes/include/Volumes_3d.h
  modules/volumes/src/Volumes_3d.cpp
Labels: Ready for merge, lab 3

#281 Гончарова - Лабораторная 3
  modules/area_calculation/CMakeLists.txt
  modules/area_calculation/CTestTests.txt
  modules/area_calculation/application/CMakeLists.txt
  modules/area_calculation/application/area_calculation.cpp
  modules/area_calculation/include/area_calculation_app.h
  modules/area_calculation/src/area_calculation_app.cpp
Labels: Ready for merge, lab 3

#264 Тычинин - Лабораторная работа #3
  modules/complex-number-calculator/CMakeLists.txt
  modules/complex-number-calculator/CTestTests.txt
  modules/complex-number-calculator/application/CMakeLists.txt
  modules/complex-number-calculator/application/complex-number-calculator.cpp
  modules/complex-number-calculator/include/complex_calculator_application.h
  modules/complex-number-calculator/include/division_by_zero_exception.h
  modules/complex-number-calculator/src/complex_calculator.cpp
  modules/complex-number-calculator/src/complex_calculator_application.cpp
Labels: Ready for merge, lab 3

#243 Силаева - Лабораторная работа 2
  modules/rb-tree/CMakeLists.txt
  modules/rb-tree/include/rb_tree.h
  modules/rb-tree/src/CMakeLists.txt
  modules/rb-tree/src/rb_tree.cpp
  modules/rb-tree/test/CMakeLists.txt
  modules/rb-tree/test/test_main.cpp
  modules/rb-tree/test/test_rb_tree.cpp
Labels: Ready for merge, lab 2

#283 Яшина - Лабораторная #3
  modules/vector_3d/CMakeLists.txt
  modules/vector_3d/CTestTests.txt
  modules/vector_3d/application/CMakeLists.txt
  modules/vector_3d/application/application.cpp
  modules/vector_3d/include/vector_3d_app.h
  modules/vector_3d/src/vector_3d_app.cpp
Labels: Ready for merge, lab 3
