Repository Teddy-Hackers/devtools-course-practice, pull requests merged in 2023-06, with the labels that each got.

#292 Гостеева - Лабораторная работа #2
  modules/Huffman_algorithm/CMakeLists.txt
  modules/Huffman_algorithm/include/HuffmanAlgorithm.h
  modules/Huffman_algorithm/src/CMakeLists.txt
  modules/Huffman_algorithm/src/HuffmanAlgorithm.cpp
  modules/Huffman_algorithm/test/CMakeLists.txt
  modules/Huffman_algorithm/test/test_huffman_algorithm.cpp
  modules/Huffman_algorithm/test/test_main.cpp
Labels: Ready for merge, lab 2

#301 Воронов-лабораторная №1
  modules/complex-number/test/test_voronov_alexandr_complex_number.cpp
Labels: Ready for merge, lab 1

#286 Миронов - Лабораторная #3
  modules/sets/CMakeLists.txt
  modules/sets/CTestTests.txt
  modules/sets/application/CMakeLists.txt
  modules/sets/application/application.cpp
  modules/sets/include/set_application.h
  modules/sets/src/set_application.cpp
Labels: Ready for merge, lab 3

#304 Кругликова - Лабораторная работа #3
  modules/intersections-line-and-plane-in-3D/include/intersections_line_and_plane.h
  modules/intersections/CMakeLists.txt
  modules/intersections/CTestTests.txt
  modules/intersections/application/CMakeLists.txt
  modules/intersections/application/intersections_line_and_plane.cpp
  modules/intersections/include/intersections_line_and_plane.h
  modules/intersections/include/intersections_line_and_plane_app.h
  modules/intersections/src/CMakeLists.txt
  modules/intersections/src/intersections_line_and_plane.cpp
  modules/intersections/src/intersections_line_and_plane_app.cpp
  modules/intersections/test/CMakeLists.txt
  modules/intersections/test/test_Lapin_Dmitriy_intersections_line_and_plane_in_3D.cpp
  modules/intersections/test/test_main.cpp
Labels: Ready for merge, lab 3

#306 Шапошникова - Лабораторная работа #1
  modules/complex-number/test/test_SHAPOSHNIKOVA_EKATERINA_complex_number.cpp
Labels: Ready for merge, lab 1

#297 Бочкарев - Лабораторная работа #3
  modules/Huffman_algorithm/CMakeLists.txt
  modules/Huffman_algorithm/CTestTests.txt
  modules/Huffman_algorithm/application/CMakeLists.txt
  modules/Huffman_algorithm/application/HuffmanAlgorithm.cpp
  modules/Huffman_algorithm/include/HuffmanAlgorithm_application.h
  modules/Huffman_algorithm/src/HuffmanAlgorithm_application.cpp
Labels: lab 3

#293 Лебединский - Лабораторная работа #3
  modules/rev_pol_not/CMakeLists.txt
  modules/rev_pol_not/CTestTests.txt
  modules/rev_pol_not/application/CMakeLists.txt
  modules/rev_pol_not/application/app.cpp
  modules/rev_pol_not/include/rev_pol_app.h
  modules/rev_pol_not/src/polish_app.cpp
Labels: Ready for merge, lab 3

#307 Пашина - Лабораторная работа #3
  modules/Matrix/CMakeLists.txt
  modules/Matrix/application/CMakeLists.txt
  modules/Matrix/application/Matrix.cpp
  modules/Matrix/include/matrix_app.h
  modules/Matrix/src/matrix_app.cpp
Labels: Ready for merge, lab 3

#308 Гостеева - Лабораторная работа #3
  modules/Function_Eyler/CMakeLists.txt
  modules/Function_Eyler/CTestTests.txt
  modules/Function_Eyler/application/CMakeLists.txt
  modules/Function_Eyler/application/Function_Eyler.cpp
  modules/Function_Eyler/include/Function_Eyler_Application.h
  modules/Function_Eyler/src/Function_Eyler.cpp
  modules/Function_Eyler/src/Function_Eyler_Application.cpp
Labels: Ready for merge, lab 3

#157 Зорин - Лабораторная работа №3
  modules/binary-tree/CMakeLists.txt
  modules/binary-tree/CTestTests.txt
  modules/binary-tree/application/CMakeLists.txt
  modules/binary-tree/application/binary_tree.cpp
  modules/binary-tree/include/binary_tree.h
  modules/binary-tree/include/binary_tree_app.h
  modules/binary-tree/src/binary_tree.cpp
  modules/binary-tree/src/binary_tree_app.cpp
  modules/binary-tree/test/test_binary_tree.cpp
Labels: lab 3

#313 Тарасова - лабораторная работа №3
  modules/sorting_array/CMakeLists.txt
  modules/sorting_array/CTestTests.txt
  modules/sorting_array/application/CMakeLists.txt
  modules/sorting_array/application/app.cpp
  modules/sorting_array/include/Application.h
  modules/sorting_array/src/Application.cpp
  modules/sorting_array/test/CMakeLists.txt
Labels: Ready for merge, lab 3

#314 Николаев - Лабораторная работа №3
  modules/interpolation_search/CMakeLists.txt
  modules/interpolation_search/CTestTests.txt
  modules/interpolation_search/application/CMakeLists.txt
  modules/interpolation_search/application/application.cpp
  modules/interpolation_search/include/interpolation_search_app.h
  modules/interpolation_search/src/interpolation_search_app.cpp
Labels: Ready for merge, lab 3

#318 Судомойкин-Лабораторная работа 2
  modules/queue/CMakeLists.txt
  modules/queue/include/queue.h
  modules/queue/src/CMakeLists.txt
  modules/queue/src/queue.cpp
  modules/queue/test/CMakeLists.txt
  modules/queue/test/queue_test.cpp
  modules/queue/test/test_main.cpp
Labels: Ready for merge, lab 2

#319 Шуин_Евгений_382008-3_ЛАБ1
  lab-guide/topics.md
  modules/complex-number/test/test_Shuin Evgeniy_complex_number.cpp
Labels: lab 1

#316 Симеунович-Лабораторная работа 2
  modules/graph_components/CMakeLists.txt
  modules/graph_components/include/graph.h
  modules/graph_components/src/CMakeLists.txt
  modules/graph_components/src/graph.cpp
  modules/graph_components/test/CMakeLists.txt
  modules/graph_components/test/test_graph_components.cpp
  modules/graph_components/test/test_main.cpp
Labels: lab 2

#321 Шуин - Лабораторная работа №2
  modules/KruskalMST/CMakeLists.txt
  modules/KruskalMST/include/KruskalMST.h
  modules/KruskalMST/src/CMakeLists.txt
  modules/KruskalMST/src/KruskalMST.cpp
  modules/KruskalMST/test/CMakeLists.txt
  modules/KruskalMST/test/test_KruskalMST.cpp
  modules/KruskalMST/test/test_main.cpp
Labels: Ready for merge, lab 2

#324 Шапошникова - Лабораторная работа #3
  modules/graph_components/CMakeLists.txt
  modules/graph_components/CTestTests.txt
  modules/graph_components/application/CMakeLists.txt
  modules/graph_components/application/Grapgh_comp_app.cpp
  modules/graph_components/include/graph_app.h
  modules/graph_components/src/graph_app.cpp
Labels: Ready for merge, lab 3

#330 Чубенко - Лабораторная работа №2
  modules/chubenko_string_calculator/CMakeLists.txt
  modules/chubenko_string_calculator/include/string_calculator.h
  modules/chubenko_string_calculator/src/CMakeLists.txt
  modules/chubenko_string_calculator/src/string_calculator.cpp
  modules/chubenko_string_calculator/test/CMakeLists.txt
  modules/chubenko_string_calculator/test/test_main.cpp
  modules/chubenko_string_calculator/test/test_string_calculator.cpp
Labels: Ready for merge, lab 2

#327 Шуин - Лабораторная работа №3
  modules/KruskalMST/CMakeLists.txt
  modules/KruskalMST/CTestTests.txt
  modules/KruskalMST/application/CMakeLists.txt
  modules/KruskalMST/application/KruskalApp.cpp
  modules/KruskalMST/include/MinimumSpanningTreeApp.h
  modules/KruskalMST/src/MinimumSpanningTreeApp.cpp
Labels: Ready for merge, lab 3

#331 Быкова Лабораторная работа 3
  modules/rb-tree/CMakeLists.txt
  modules/rb-tree/CTestTests.txt
  modules/rb-tree/application/CMakeLists.txt
  modules/rb-tree/application/rb_tree.cpp
  modules/rb-tree/include/rb_operation.h
  modules/rb-tree/include/rb_tree_application.h
  modules/rb-tree/src/rb_operation.cpp
  modules/rb-tree/src/rb_tree.cpp
  modules/rb-tree/src/rb_tree_application.cpp
  modules/rb-tree/test/test_rb_tree_application.cpp
Labels: Ready for merge, lab 3

#332 Терентьев - Лабораторная работа #1
  modules/complex-number/test/test_Terentev_Alexandr_complex_number .cpp
Labels: Ready for merge, lab 1

#333 Чубенко - Лабораторная работа №3
  modules/chubenko_string_calculator/CMakeLists.txt
  modules/chubenko_string_calculator/CTestTests.txt
  modules/chubenko_string_calculator/application/CMakeLists.txt
  modules/chubenko_string_calculator/application/application.cpp
  modules/chubenko_string_calculator/include/string_calculator_app.h
  modules/chubenko_string_calculator/src/string_calculator_app.cpp
Labels: Ready for merge, lab 3

#274 Быкова - Лабораторная работа 2
  modules/d-heap/CMakeLists.txt
  modules/d-heap/include/DHeap.h
  modules/d-heap/src/CMakeLists.txt
  modules/d-heap/src/DHeap.cpp
  modules/d-heap/test/CMakeLists.txt
  modules/d-heap/test/test_heap.cpp
  modules/d-heap/test/test_main.cpp
Labels: Ready for merge, lab 2

#337 Судомойкин-Лабораторная работа 1
  modules/complex-number/test/test_Sudomoykin_Andrey_complex_number.cpp
Labels: Ready for merge, lab 1

#339 Хайретдинов - Лабораторная работа #1
  modules/complex-number/test/test_KHAIRETDINOV_TIMUR_complex_number.cpp
Labels: Ready for merge, lab 1

#342 Хайретдинов - Лабораторная работа #2
  modules/graph_diameter/CMakeLists.txt
  modules/graph_diameter/include/graph_diameter.h
  modules/graph_diameter/src/CMakeLists.txt
  modules/graph_diameter/src/graph_diameter.cpp
  modules/graph_diameter/test/CMakeLists.txt
  modules/graph_diameter/test/graph_diameter_test.cpp
  modules/graph_diameter/test/test_main.cpp
Labels: Ready for merge, lab 2

#335 Симеунович-Лабораторная работа 3
  modules/comb_gen/CMakeLists.txt
  modules/comb_gen/CTestTests.txt
  modules/comb_gen/application/CMakeLists.txt
  modules/comb_gen/application/main.cpp
  modules/comb_gen/include/Comb_gen_app.h
  modules/comb_gen/src/Comb_gen_app.cpp
Labels: Ready for merge, lab 3

#334 Силаева - Лабораторная работа 3
  modules/d-heap/CMakeLists.txt
  modules/d-heap/CTestTests.txt
  modules/d-heap/application/CMakeLists.txt
  modules/d-heap/application/application.cpp
  modules/d-heap/include/DHeap_application.h
  modules/d-heap/src/DHeap_application.cpp
Labels: Ready for merge, lab 3

#346 Резчиков - Лабораторная работа #3
  modules/long_numbers/CMakeLists.txt
  modules/long_numbers/CTestTests.txt
  modules/long_numbers/application/CMakeLists.txt
  modules/long_numbers/application/helloworld.cpp
  modules/long_numbers/include/long_num.h
  modules/long_numbers/include/long_num_app.h
  modules/long_numbers/src/CMakeLists.txt
  modules/long_numbers/src/long_num.cpp
  modules/long_numbers/src/long_num_app.cpp
  modules/long_numbers/test/CMakeLists.txt
  modules/long_numbers/test/test_long_num.cpp
  modules/long_numbers/test/test_main.cpp
Labels: Ready for merge, lab 3

#341 Резчиков - Лабораторная работа #2
  modules/bilinear_interpolation/CMakeLists.txt
  modules/bilinear_interpolation/include/bilinear_interpolation.h
  modules/bilinear_interpolation/src/CMakeLists.txt
  modules/bilinear_interpolation/src/bilinear_interpolation.cpp
  modules/bilinear_interpolation/test/CMakeLists.txt
  modules/bilinear_interpolation/test/test_bilinear.cpp
  modules/bilinear_interpolation/test/test_main.cpp
Labels: Ready for merge, lab 2

#348 Антонова - Лабораторная работа №2
  modules/BigInt/CMakeLists.txt
  modules/BigInt/include/bigInt.h
  modules/BigInt/src/CMakeLists.txt
  modules/BigInt/src/bigInt.cpp
  modules/BigInt/test/CMakeLists.txt
  modules/BigInt/test/test_bigInt.cpp
  modules/BigInt/test/test_main.cpp
Labels: Ready for merge, lab 2

#350 Антонова - Лабораторная работа №3
  modules/hanoi-tower/CTestTests.txt
  modules/hanoi-tower/application/CMakeLists.txt
  modules/hanoi-tower/application/Hanoi.cpp
  modules/hanoi-tower/include/Hanoi_application.h
  modules/hanoi-tower/src/Hanoi_application.cpp
Labels: Ready for merge, lab 3
