Repository Teddy-Hackers/devtools-course-practice, pull requests merged in 2023-04, with the labels that each got.

#1 Add labeler bot
  label_bot/index.js
  label_bot/package.json
Labels: Ready for merge

#2 Кандрин - Лабораторная работа #2 (выбор темы)
  lab-guide/topics.md
Labels: Ready for merge

#29 Кандрин - Лабораторная работа #1
  modules/complex-number/test/test_KANDRIN_ALEXEY_complex_number.cpp
Labels: Ready for merge

#37 Кандрин - Лабораторная работа #2
  modules/stack/CMakeLists.txt
  modules/stack/README.md
  modules/stack/include/list.h
  modules/stack/include/stack.h
  modules/stack/src/CMakeLists.txt
  modules/stack/src/list.cpp
  modules/stack/src/stack.cpp
  modules/stack/test/CMakeLists.txt
  modules/stack/test/test_list.cpp
  modules/stack/test/test_main.cpp
  modules/stack/test/test_stack.cpp
Labels: Ready for merge

#30 Колесов - Лабораторная работа #1
  modules/complex-number/test/test_MAKSIM_KOLESOV_complex_number.cpp
Labels: Ready for merge

#33 Селиванкин - Лабораторная работа #1
  modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
Labels: Ready for merge, lab 1

#31 Зорин - Лабораторная работа #1
  modules/complex-number/test/test_ZORIN_OLEG_complex_number.cpp
Labels: Ready for merge, lab 1

#36 Колесов - Лабораторная работа #2
  modules/caesar-cipher/CMakeLists.txt
  modules/caesar-cipher/include/cipher.h
  modules/caesar-cipher/src/CMakeLists.txt
  modules/caesar-cipher/src/cipher.cpp
  modules/caesar-cipher/test/CMakeLists.txt
  modules/caesar-cipher/test/test_cipher.cpp
  modules/caesar-cipher/test/test_main.cpp
Labels: Ready for merge, lab 2

#49 Юрин - Лабораторная работа #1
  modules/complex-number/test/test_Yurin_Evgeny_complex_number.cpp
Labels: Ready for merge, lab 1

#51 Попов А.А - Лабораторная работа #1
  modules/complex-number/test/test_Popov_Andrey_complex_number.cpp
Labels: Ready for merge, lab 1

#35 Устинов - Лабораторная работа #1
  modules/complex-number/test/test_ustinov_alexandr_complex_number.cpp
Labels: Ready for merge, lab 1

#57 Шокуров - Лабораторная работа #1
  modules/complex-number/test/test_SHOKUROV_DANIIL_complex_number.cpp
Labels: Ready for merge, lab 1

#58 Терина - Лабораторная работа #1
  modules/complex-number/test/test_TERINA_ALINA_complex_number.cpp
Labels: Ready for merge, lab 1

#71 Николаев - Лабораторная работа #1
  modules/complex-number/test/test_NIKOLAEV_ALEXANDER_complex_number.cpp
Labels: Ready for merge, lab 1

#55 Булгаков - Лабораторная работа #1
  modules/complex-number/test/test_BULGAKOV_DANIIL_complex_number.cpp
Labels: Ready for merge, lab 1

#84 Миронов - Лабораторная работа #1
  modules/complex-number/test/test_MIRONOV_NIKITA_complex_number.cpp
Labels: Ready for merge, lab 1

#53 Зорин - Лабораторная работа #2
  modules/priority-queue/CMakeLists.txt
  modules/priority-queue/include/priority_queue.h
  modules/priority-queue/src/CMakeLists.txt
  modules/priority-queue/src/priority_queue.cpp
  modules/priority-queue/test/CMakeLists.txt
  modules/priority-queue/test/test_main.cpp
  modules/priority-queue/test/test_priority_queue.cpp
Labels: Ready for merge, lab 2

#96 Семенова - Лабораторная работа №1
  modules/complex-number/test/test_SEMENOVA_VERONIKA_complex_number.cpp
Labels: Ready for merge, lab 1

#86 Тычинин - Лабораторная работа #1
  modules/complex-number/test/test_Tychinin_Alexey_complex_number.cpp
Labels: Ready for merge, lab 1

#92 Костерин - Лабораторная работа #1
  modules/complex-number/test/test_kosterin_a_complex_number.cpp
Labels: Ready for merge, lab 1

#72 Коробейникова - Лабораторная работа #1
  modules/complex-number/test/test_KOROBEYNIKOVA_ALICE_complex_number.cpp
Labels: Ready for merge, lab 1

#67 Тарасова - Лабораторная работа #1
  modules/complex-number/test/test_TARASOVA_ANASTASIYA_complex_number.cpp
Labels: Ready for merge, lab 1

#85 Ивлев - Лабораторная работа #1
  modules/complex-number/test/test_IVLEV_ALEXANDER_complex_number.cpp
Labels: Ready for merge, lab 1

#47 Селиванкин - Лабораторная работа #2
  modules/binary-search/CMakeLists.txt
  modules/binary-search/include/binary_search.h
  modules/binary-search/src/CMakeLists.txt
  modules/binary-search/src/binary_search.cpp
  modules/binary-search/test/CMakeLists.txt
  modules/binary-search/test/test_binary_search.cpp
  modules/binary-search/test/test_main.cpp
Labels: Ready for merge, lab 2

#94 Коробейникова - Лабораторная работа #2
  modules/point-falls-into-a-triangle/CMakeLists.txt
  modules/point-falls-into-a-triangle/include/triangle.h
  modules/point-falls-into-a-triangle/src/CMakeLists.txt
  modules/point-falls-into-a-triangle/src/triangle.cpp
  modules/point-falls-into-a-triangle/test/CMakeLists.txt
  modules/point-falls-into-a-triangle/test/test_main.cpp
  modules/point-falls-into-a-triangle/test/test_point-falls-into-a-triangle.cpp
Labels: Ready for merge, lab 2

#98 Никитин - Лабораторная работа #1
  modules/complex-number/test/test_Nikitin_Aleksandr_complex_number.cpp
Labels: Ready for merge, lab 1

#104 Елистратов - Лабораторная работа #1
  modules/complex-number/test/test_Elistratov_Vladimir_complex_number.cpp
Labels: Ready for merge, lab 1

#101 Макаров - Лабораторная работа #1
  modules/complex-number/test/test_Makarov_Danila_complex_number.cpp
Labels: Ready for merge, lab 1

#105 Ермолаев - Лабораторная работа #1
  modules/complex-number/test/test_Ermolaev_Danila_complex_number.cpp
Labels: Ready for merge, lab 1

#106 Французов - Лабораторная работа #1
  modules/complex-number/test/test_Frantcuzov-Maksim-complex_number.cpp
Labels: Ready for merge, lab 1

#107 Еремин - Лабораторная работа #1
  modules/complex-number/test/test_Eremin_Aleksandr_complex_number.cpp
Labels: Ready for merge, lab 1

#111 Резчиков - Лабораторная работа #1
  modules/complex-number/test/test_REZCHIKOV_DMITRII_complex_number.cpp
Labels: Ready for merge, lab 1

#112 Митин - Лабораторная работа #1
  modules/complex-number/test/test_MITIN_ROMAN_complex_number.cpp
Labels: Ready for merge, lab 1

#113 Силаева- Лабораторная работа №1
  modules/complex-number/test/test_SILAEVA_NATALYA_complex_number.cpp
Labels: Ready for merge, lab 1

#114 Шипилов - Лабораторная работа #1
  modules/complex-number/test/test_Shipilov_Artem_complex_number.cpp
Labels: Ready for merge, lab 1

#116 Бинько - Лабораторная работа #1
  modules/complex-number/test/test_Binko_Alexandr_complex_number.cpp
Labels: Ready for merge, lab 1

#119 Быкова - Лабораторная №1
  modules/complex-number/test/test_Bykova_Aleksandra_complex_number.cpp
Labels: Ready for merge, lab 1

#76 Уваркин - Лабораторная работа #1
  modules/complex-number/test/test_UVARKIN_ILYA_complex_number.cpp
Labels: Ready for merge, lab 1

#99 Коробейникова - Лабораторная работа #3
  modules/stack/CMakeLists.txt
  modules/stack/CTestTests.txt
  modules/stack/application/CMakeLists.txt
  modules/stack/application/stack.cpp
  modules/stack/include/stack_app.h
  modules/stack/src/stack_app.cpp
Labels: Ready for merge, lab 3

#110 Устинов - Лабораторная работа #2
  modules/longest-increasing-subsequence/CMakeLists.txt
  modules/longest-increasing-subsequence/README.md
  modules/longest-increasing-subsequence/include/longest_inc_subseq.h
  modules/longest-increasing-subsequence/src/CMakeLists.txt
  modules/longest-increasing-subsequence/src/longest_inc_subseq.cpp
  modules/longest-increasing-subsequence/test/CMakeLists.txt
  modules/longest-increasing-subsequence/test/test_main.cpp
  modules/longest-increasing-subsequence/test/test_ustinov_alexandr_longest_increasing_subsequence.cpp
Labels: Ready for merge, lab 2
