Repository Teddy-Hackers/devtools-course-practice, pull requests merged in 2023-10, with the labels that each got.

#351 Асосков - Лабораторная работа №1 (пересдача)
  modules/complex-number/test/test_ASOSKOV_MIKHAIL_complex_number.cpp
Labels: lab 1

#352 Асосков - Лабораторная работа №2 (пересдача)
  modules/array_permutation_generator/CMakeLists.txt
  modules/array_permutation_generator/include/array_permutation.h
  modules/array_permutation_generator/src/CMakeLists.txt
  modules/array_permutation_generator/src/array_permutation.cpp
  modules/array_permutation_generator/test/CMakeLists.txt
  modules/array_permutation_generator/test/test_array_permutation.cpp
  modules/array_permutation_generator/test/test_main.cpp
Labels: Ready for merge, lab 2

#359 Ильин Максим - Лабораторная работа №1
  modules/complex-number/test/test_ilyin_maksim_complex_number.cpp
Labels: lab 1

#363 Козлов Алексей - Лабораторная работа №1
  modules/complex-number/test/test_kozlov_aleksey_complex_number.cpp
Labels: lab 1

#366 Асосков Михаил - Лабораторная работа №3 (пересдача)
  modules/bilinear_interpolation/CMakeLists.txt
  modules/bilinear_interpolation/CTestTests.txt
  modules/bilinear_interpolation/application/CMakeLists.txt
  modules/bilinear_interpolation/application/app_bilinear_interpolation.cpp
  modules/bilinear_interpolation/include/bilinear_interpolation_app.h
  modules/bilinear_interpolation/src/bilinear_interpolation_app.cpp
Labels: Ready for merge, lab 3

#356 Матвеев Сергей - Лабораторная работа №2
  modules/template_binary_heap/CMakeLists.txt
  modules/template_binary_heap/include/template_heap.h
  modules/template_binary_heap/src/CMakeLists.txt
  modules/template_binary_heap/src/template_heap.cpp
  modules/template_binary_heap/test/CMakeLists.txt
  modules/template_binary_heap/test/test_main.cpp
  modules/template_binary_heap/test/test_template_heap.cpp
Labels: lab 2

#358 Матвеев Сергей - Лабораторная работа №3
  modules/AVL-Tree/CMakeLists.txt
  modules/AVL-Tree/CTestTests.txt
  modules/AVL-Tree/application/CMakeLists.txt
  modules/AVL-Tree/application/application.cpp
  modules/AVL-Tree/include/AVLTree.h
  modules/AVL-Tree/include/AVLTree_app.h
  modules/AVL-Tree/src/AVLTree_app.cpp
Labels: lab 3

#367 Мельник Денис - Лабораторная работа №1
  modules/complex-number/test/test_MELNIK_DENIS_complex_number.cpp
Labels: lab 1

#371 Kuznetsov sergey lab1
  modules/complex-number/test/test_KUZNETSOV_SERGEY_complex_number.cpp
Labels: lab 1

#376 Yashin egor lab1
  modules/complex-number/test/test_Yashin_Egor_complex_number.cpp
Labels: lab 1

#372 Larin Konstantin Lab1
  3rdparty/gtest/gtest-all.cc
  modules/complex-number/test/test_Larin_Konstantin_complex_number.cpp
Labels: lab 1
